name: RunPythonScript

on:
  schedule:
    - cron: '0 7 * * *' # Runs at 11:00 AM Nepal Standard Time (UTC +5:45)

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Python environment
        uses: actions/setup-python@v4
        with:
          python-version: '3.10' # Update based on your needs
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Run Python script
        run: python main.py